###
GET http://localhost:3001/api/notes/63fcee0ddd0bf990317339b7

###
DELETE http://localhost:3001/api/notes/63fcee0ddd0bf990317339b7

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "RSTIII",
    "important": true
}
###
PUT http://localhost:3001/api/notes/63fcee0ddd0bf990317339b7
Content-Type: application/json

{
    "content": "kokeilu2",
    "important": true
}