###
GET http://localhost:3001/api/users/65d36564a522c7f854207966

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "lauri",
    "password": "salasana"
}

###
PUT http://localhost:3001/api/users/65d36564a522c7f854207966
Content-Type: application/json

{
    "product": "642c17f0c7c74461746014ce"
}

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "sello1",
    "password": "salasana"
}