###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "lauri",
    "password": "salasana"
}

###
PUT http://localhost:3001/api/users/65d4f6e534f2e0a79eedcb48
Content-Type: application/json

{
    "product": [{
        "name": "kilpi",
        "price": 13,
        "category": "armor",
        "id": "642be8eeb8d16e97931346c9"
    }]
}

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "sello1",
    "password": "salasana"
}