###
GET http://localhost:3001/api/users/64f6c4d33210a4639c29c16e

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "lauri",
    "password": "salasana"
}

###
PUT http://localhost:3001/api/users/64f6c4d33210a4639c29c16e
Content-Type: application/json

{
    "username": "uusi",
    "password": "salasana",
    "cart": ["hello"]
}

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "sello",
    "password": "aenvn"
}