###
GET http://localhost:3001/api/products/


###
DELETE http://localhost:3001/api/notes/641885209842e90d1f4a125a

###
POST http://localhost:3001/api/products/
Content-Type: application/json

{
    "name": "kirves",
    "price": "13657",
    "category": "ase"
}
###
PUT http://localhost:3001/api/products/642c17f0c7c74061746014ce
Content-Type: application/json

{
    "name": "upgraded keihäs",
    "price": "14",
    "category": "range"
}